services:
  mysql:
    container_name: prestashop-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
  prestashop:
    container_name: prestashop
    build: .
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - ${PS_PORT}:80
      - 8443:443
    environment:
      PS_DEV_MODE: 1
      DB_SERVER: prestashop-mysql
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_FOLDER_INSTALL: ${PS_FOLDER_INSTALL}
    networks:
      - prestashop_network
    command: /bin/bash -c "a2enmod ssl && apache2-foreground"
    volumes:
      - ./prestashop:/var/www/html
      - ./ssl/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./ssl/certs:/etc/ssl/certs
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        PMA_HOST: prestashop-mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: unless-stopped
      ports:
        - ${PMA_PORT}:80
      networks:
        - prestashop_network
networks:
  prestashop_network:
volumes:
  dbdata: